<?php
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);
	
	include('common_function.php');
	
	if(is_ajax()) {
		if(isset($_POST["action"]) && !empty($_POST["action"])) {
			$action = $_POST["action"];
			switch($action) {
				/* ITN */
				case "get_control_no_itn_display"						: get_control_no_itn_display(); break;
				case "get_itn_details"									: get_itn_details(); break;
				case "save_itn"											: save_itn(); break;
				case "update_itn"										: update_itn(); break;
				case "change_status_itn"								: change_status_itn(); break;
				case "lqc_supervisor_update_status"						: lqc_supervisor_update_status(); break;
				case "engineering_production_supervisor_update_status"	: engineering_production_supervisor_update_status(); break;
				case "lqc_result_of_confirmation_update_status"			: lqc_result_of_confirmation_update_status(); break;
			}
		}
	}

	function is_ajax() {
		return isset($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest';
	}
	
	/* 
		ITN - Inspection Trouble Report 
	*/
	function save_itn(){
		require_once('../class/oop_tqts.php');
		$control_no 			= generate_itn_issuance_no( date('Y-m-d H:i:s'), $_POST['username'] );
		/* get all fields in table */
		$table_fields 			= get_table_fields('tbl_qfr_itn');
		$return['table_fields'] = $table_fields;
		$error = array();
		/* assign blank to all fields that has not been initialized on submit */
		foreach($table_fields as $key => $fields){
			if(!isset($_POST[$fields])){ $_POST[$fields] = ''; }
		}
		
		$array_select2_multiple = array('attention','fp_conformed_by','a_validated_by','ca_responsible','rc_responsible');
		foreach($_POST as $key => $value){
			if(in_array($key,$array_select2_multiple)){
				$_POST[$key]		= implode('|',$value);
			}
		}
		$_POST['lastupdate']	= date('Y-m-d H:i:s');
		$_POST['date_created']	= date('Y-m-d H:i:s');
		$_POST['created_by']	= $_POST['username'];
		$_POST['status']		= 0;
		$return 				= $_POST;
		$array_fields_values 	= get_fields_values( $_POST, array("pkid","logdel","action","control_no") );
		$return['array_fields_values'] 	= $array_fields_values;
		/* save itn if no error was encountered */
		if( count($error) == 0 ){
			$table			= 'tbl_qfr_itn';
			$array_fields	= $array_fields_values['array_fields'];
			$array_values	= $array_fields_values['array_values'];
			$array_fields[] = 'control_no'; 	$array_values[] = $control_no;
			$pkid 			= TQTS::getInstance()->insert_query_id($table,$array_fields,$array_values);
			$script 		= TQTS::getInstance()->insert_query_id_script($table,$array_fields,$array_values);
			/* Send mail to mailer */
			$row_data 	= get_itn_row_data($pkid);
			$mail_data  = array();
			$to_email 	= array();
			$attention  = explode('|',$row_data['attention']);
			foreach($attention as $key => $username){
				$to_email[] = return_user_email_add($username);
			}
			$fp_inspected_by  = $row_data['fp_inspected_by'];
			if(!in_array($fp_inspected_by,$to_email)){
				$to_email[] = return_user_email_add($fp_inspected_by);
			}
			$fp_verfied_by  = $row_data['fp_verfied_by'];
			if(!in_array($fp_verfied_by,$to_email)){
				$to_email[] = return_user_email_add($fp_verfied_by);
			}
			$fp_conformed_by  = explode('|',$row_data['fp_conformed_by']);
			foreach($fp_conformed_by as $key => $username){
				if(!in_array(return_user_email_add($username),$to_email)){
					$to_email[] = return_user_email_add($username);
				}
			}
			$cc_email 	= array();
			// foreach($cc as $key => $username){
				// $cc_email[] = return_user_email_add($username);
			// }
			$to_email    = implode(",",$to_email);
			$cc_email    = implode(",",$cc_email);
			$bcc		 = 'marlope@pricon.ph,ronfern@pricon.ph';
			$from		 = 'issinforservice@pricon.ph';
			$from_name	 = 'TQTS Mailer';
			$subject	 	= "Inspection Trouble Notice - ".$control_no;
			$message 	 = 'Good Day! <br><br>';
			$message 	.= 'ITN Details: <br>';
			$message 	.= 'Project: '.$row_data['project'].'<br>';
			$message 	.= 'Model: '.$row_data['model'].'<br>';
			$message 	.= 'Issuance Date: '.$row_data['issuance_date'].'<br>';
			$message 	.= 'Standard Specifications: '.$row_data['standard_specification'].'<br>';
			$message 	.= 'Findings Problem: '.$row_data['findings_problem'].'<br>';
			$message 	.= '<br>Please login to Rapid with this link http://rapid <br><br>';
			$message 	.= 'This is a system message generated by the system, Please do not reply!';
			$send_date_time = date('Y-m-d H:i:s');
			require_once('../class/send_email.php');
			$email = new email;
			// $mailer_result = $email->send_email_detailed($to_email, $from, $from_name, $cc_email, $bcc, $subject, $message, $send_date_time, $_POST['username']);
			$return['mail_data'] 		= $mailer_result;
			/* Send mail to mailer - end */
			$return['script'] 		= $script;
		}		
		$return['error'] 		= $error;
		echo json_encode($return);
	}
	
	function generate_itn_issuance_no($date,$username){
		require_once('../class/oop_tqts.php');
		$division 	= return_system_division();
		$section 	= get_assigned_section_itn($username);
		$array_fields = array('control_no');
		$table 	   	= 'tbl_qfr_itn';
		$joins 	   	= '';
		$sql_where 	= 'WHERE date_created LIKE "%'.date('Y').'-%" AND logdel=0';
		$sql_order 	= 'ORDER BY pkid DESC';
		$sql_limit 	= 'LIMIT 0,1';
		$issuance_no= '';
		$result = TQTS::getInstance()->select_query($array_fields,$table,$joins,$sql_where,$sql_order,$sql_limit);
		$script = TQTS::getInstance()->select_query_script($array_fields,$table,$joins,$sql_where,$sql_order,$sql_limit);
		if($result->num_rows==0) {
			$issuance_no = $division.'-'.$section.'-'.date('ym').'-001';
		} else {
			if($row = mysqli_fetch_array($result)) {
				$issuance_no = $row['control_no'];
				$ctr 		 	= end(explode('-',$issuance_no));
				$series 	 	= '-'.str_pad(($ctr+1),3,"0",STR_PAD_LEFT);
			}		
			$issuance_no = $division.'-'.$section.'-'.date('ym').$series;
		}
		if(is_array($section)){
			$issuance_no = array();
			$issuance_no['error'] = $section['error'];
		}
		return $issuance_no;
	}
	
	function get_assigned_section_itn($username) {
		require_once('../class/oop_tqts.php');
		$array_fields = array('section');
		$table      = 'vw_user_roles';
		$joins      = '';
		$sql_where  = 'WHERE subsystem_code="QFR" AND module="ITN" AND `user`="'.$username.'"';
		$sql_order  = 'ORDER BY section';
		$sql_limit  = 'LIMIT 0,1';
		$result 	= TQTS::getInstance()->select_query($array_fields,$table,$joins,$sql_where,$sql_order,$sql_limit);
		$section  	= '';
		if($row=mysqli_fetch_array($result)) {
			if($row['section'] != ''){
				$section = $row['section'];
			}else{
				$section = array();
				$section['error']	= 'No section assigned to employee, please contact ISS Loc(205)!';
			}
		} else {
			$section = array();
			$section['error']		= 'No section assigned to employee, please contact ISS Loc(205)!';
		}
		return $section;
	 }
	 
	 function get_control_no_itn_display(){
		$control_no = generate_itn_issuance_no( date('Y-m-d H:i:s'), $_POST['username'] );
		$error = '';
		if(is_array($control_no)){
			$error 				= $control_no['error'];
		}
		$return['error'] 		= $error;
		$return['control_no'] 	= $control_no;
		echo json_encode($return);
	 }
	 
	 function get_itn_details(){
		 require_once('../class/oop_tqts.php');
		 $pkid   = $_POST['pkid'];
		 $table  = "tbl_qfr_itn";
		 $fields = get_table_fields($table);
		 $array_fields = array('*');
		 $table  		= "tbl_qfr_itn";
		 $joins  	 	= "";
		 $sql_where  	= "WHERE `pkid` = '$pkid'";
		 $sql_order  	= "";
		 $sql_limit  	= "";
		 $result        = TQTS::getInstance()->select_query($array_fields,$table,$joins,$sql_where,$sql_order,$sql_limit);
		 $return        = array();
		 $array_select2_single = array('fp_inspected_by','fp_verfied_by');
		 $array_select2_multiple = array('attention','fp_conformed_by','a_validated_by','ca_responsible','rc_responsible');
		 $array_date 	= array('issuance_date','return_date','a_validated_by','a_date','ca_date','rc_date');
		 while($row = mysqli_fetch_array($result)){
			 foreach($fields as $key => $value){
				 /* check if value is a selectbox */
				 if(in_array($value,$array_select2_single)){
					$array_select2_data = array();
					$array_names 		= explode("|",$row[$value]);
					foreach($array_names as $key_names => $name){
						$select2_data 	= array(
							"id"	=> $name,
							"text"	=> get_emp_name_by_username_systemone($name)
						);
						$array_select2_data[] = $select2_data;
					}				
					$return[$value] = $array_select2_data;
				}else if(in_array($value,$array_select2_multiple)){
					$array_select2_data = array();
					$array_names 		= explode("|",$row[$value]);
					foreach($array_names as $key_names => $name){
						$select2_data 	= array(
							"id"	=> $name,
							"text"	=> get_emp_name_by_username_systemone($name)
						);
						$array_select2_data[] = $select2_data;
					}				
					$return[$value."[]"] = $array_select2_data;
				}else if(in_array($value,$array_date)){
					if( $row[$value] == ""){
						$return[$value] = "";
					}else{
						$return[$value] = date('Y-m-d', strtotime($row[$value]));
					}
					 
				 }else{
					$return[$value] = $row[$value];
				 }
			 }
		 }
		 echo json_encode($return);
	 }
	 
	 function get_itn_row_data($pkid){
	    $table  = "tbl_qfr_itn";
		$fields = get_table_fields($table);
		$array_fields = array('*');
		$table  		= "tbl_qfr_itn";
		$joins  	 	= "";
		$sql_where  	= "WHERE `pkid` = '$pkid' AND logdel='0'";
		$sql_order  	= "";
		$sql_limit  	= "";
		$result        = TQTS::getInstance()->select_query($array_fields,$table,$joins,$sql_where,$sql_order,$sql_limit);
		$script        = TQTS::getInstance()->select_query_script($array_fields,$table,$joins,$sql_where,$sql_order,$sql_limit);
		$row_data 		= array();
		while($row = mysqli_fetch_assoc($result)){
			$row_data = $row;
		}
		return $row_data;
	 }
	 
	 function update_itn(){
		require_once('../class/oop_tqts.php');
		$error = '';
		/* update itn if no error was encountered */
		if( $error == '' ){
			$array_select2_multiple = array('attention','fp_conformed_by','a_validated_by','ca_responsible','rc_responsible');
			foreach($_POST as $key => $value){
				if(in_array($key,$array_select2_multiple)){
					$_POST[$key]		= implode('|',$value);
				}
			}
			$values			= get_fields_values($_POST, array('action','control_no'));
			$pkid 			= $_POST['pkid'];
			$table			= 'tbl_qfr_itn';
			$array_fields	= $values['array_fields'];
			$array_values	= $values['array_values'];
			$array_fields[] = 'lastupdate'; 	$array_values[] = date('Y-m-d H:i:s');
			$array_fields[] = 'username'; 		$array_values[] = $_POST['username'];
			if(!isset($_POST['shift_a'])){		$array_fields[] = 'shift_a'; 		$array_values[] = 0; }
			if(!isset($_POST['shift_b'])){ 		$array_fields[] = 'shift_b'; 		$array_values[] = 0; }
			if(!isset($_POST['shift_c'])){ 		$array_fields[] = 'shift_c'; 		$array_values[] = 0; }
			if(!isset($_POST['gate'])){    		$array_fields[] = 'gate'; 			$array_values[] = 0; }
			if(!isset($_POST['surveillance'])){ $array_fields[] = 'surveillance'; 	$array_values[] = 0; }
			if(!isset($_POST['normal'])){    	$array_fields[] = 'normal'; 		$array_values[] = 0; }
			if(!isset($_POST['tightened'])){    $array_fields[] = 'tightened'; 		$array_values[] = 0; }
			if(!isset($_POST['reduced'])){    	$array_fields[] = 'reduced'; 		$array_values[] = 0; }
			$result 		= TQTS::getInstance()->update_query($table,$array_fields,$array_values,$pkid);
		}
		$return['POST'] 		= $_POST;
		$return['msg'] 			= $result;
		$return['error'] 		= $error;
		echo json_encode($return);
	 }
	 
	 function change_status_itn(){
		require_once('../class/oop_tqts.php');
		$error = '';
		/* update itn if no error was encountered */
		if( $error == '' ){
			$pkid 			= $_POST['pkid'];
			$status 		= $_POST['status'];
			$table			= 'tbl_qfr_itn';
			$array_fields   = array('status');
			if($status == "Open"){
				$array_values   = array('Closed');
			}else{
				$array_values   = array('Open');
			}
			$array_fields[] = 'lastupdate'; 	$array_values[] = date('Y-m-d H:i:s');
			$array_fields[] = 'username'; 		$array_values[] = $_POST['username'];
			$result 		= TQTS::getInstance()->update_query($table,$array_fields,$array_values,$pkid);
		}
		$return = array();
		$return['POST'] 		= $_POST;
		$return['result'] 		= $result;
		$return['error'] 		= $error;
		echo json_encode($return);
	 }
	 
	 function lqc_supervisor_update_status(){
		require_once('../class/oop_tqts.php');
		$return = $_POST;
		$pkid 	= $_POST['pkid'];
		$fp_verfied_by_approval_status = $_POST['status'];
		$username = $_POST['username'];
		if($fp_verfied_by_approval_status == 1){
			$status = '1';
		}else{
			$status = '9';
		}
		$remarks = $_POST['remarks'];
		$table	= 'tbl_qfr_itn';
		$array_fields = array('fp_verfied_by_approval_status','remarks','status','username','lastupdate');
		$array_values = array($fp_verfied_by_approval_status,$remarks,$status,$username,date('Y-m-d H:i:s'));
		$result = TQTS::getInstance()->update_query($table,$array_fields,$array_values,$pkid);
		$script = TQTS::getInstance()->update_query_script($table,$array_fields,$array_values,$pkid);
		$return['script'] = $script;
		/* Send mail to mailer */
		$row_data 	= get_itn_row_data($pkid);
		$mail_data  = array();
		$to_email 	= array();
		$a_validated_by  = explode('|',$row_data['a_validated_by']);
		foreach($a_validated_by as $key => $username){
			$to_email[] = return_user_email_add($username);
		}	
		$ca_responsible  = explode('|',$row_data['ca_responsible']);
		foreach($ca_responsible as $key => $username){
			if(!in_array(return_user_email_add($username),$to_email)){
				$to_email[] = return_user_email_add($username);
			}			
		}
		$cc_email 	 = array();
		$to_email    = implode(",",$to_email);
		$cc_email    = implode(",",$cc_email);
		$bcc		 = 'marlope@pricon.ph,ronfern@pricon.ph';
		$from		 = 'issinforservice@pricon.ph';
		$from_name	 = 'TQTS Mailer';
		$subject	 = "Inspection Trouble Notice - ".$row_data['control_no'];
		$message 	 = 'Good Day! <br><br>';
		$message 	.= 'ITN Details: - PENDING - (Analysis and Corrective Action)<br>';
		$message 	.= 'Project: '.$row_data['project'].'<br>';
		$message 	.= 'Model: '.$row_data['model'].'<br>';
		$message 	.= 'Issuance Date: '.$row_data['issuance_date'].'<br>';
		$message 	.= 'Standard Specifications: '.$row_data['standard_specification'].'<br>';
		$message 	.= 'Findings Problem: '.$row_data['findings_problem'].'<br>';
		$message 	.= '<br>Please login to Rapid with this link http://rapid <br><br>';
		$message 	.= 'This is a system message generated by the system, Please do not reply!';
		$send_date_time = date('Y-m-d H:i:s');
		require_once('../class/send_email.php');
		$email = new email;
		$mailer_result = $email->send_email_detailed($to_email, $from, $from_name, $cc_email, $bcc, $subject, $message, $send_date_time, $_POST['username']);
		$return['mail_data'] 		= $mailer_result;
		/* Send mail to mailer - end */		
		echo json_encode($return);
	 }
	 
	 function engineering_production_supervisor_update_status(){
		require_once('../class/oop_tqts.php');
		$error							= array();
		$return							= $_POST;
		$pkid 							= $_POST['pkid'];
		if( ($_POST['analysis'] != "") && (str_replace(" ", "", $_POST['analysis']) == "") ){
			$error[] = "Analysis could not be blank!";
		}
		if( ($_POST['corrective_action'] != "") && (str_replace(" ", "", $_POST['corrective_action']) == "") ){
			$error[] = "Corrective action could not be blank!";
		}
		if( count($error) != 0 ){
			$return['error'] = $error;
			echo json_encode($return);
			exit;
		}
		$_POST['status']				= '2';
		$_POST['a_date']				= date('Y-m-d H:i:s');
		$_POST['ca_date']				= date('Y-m-d H:i:s');
		$table							= 'tbl_qfr_itn';
		$array_field_values 			= get_fields_values($_POST,array('action','pkid'));
		$array_fields 					= $array_field_values['array_fields'];
		$array_values 					= $array_field_values['array_values'];
		$result = TQTS::getInstance()->update_query($table,$array_fields,$array_values,$pkid);
		$script = TQTS::getInstance()->update_query_script($table,$array_fields,$array_values,$pkid);
		$return['script'] = $script;
		/* Send mail to mailer */
		$row_data 	= get_itn_row_data($pkid);
		$mail_data  = array();
		$to_email 	= array();
		$rc_responsible  = explode('|',$row_data['rc_responsible']);
		foreach($rc_responsible as $key => $username){
			$to_email[] = return_user_email_add($username);
		}	
		$cc_email 	 = array();
		$to_email    = implode(",",$to_email);
		$cc_email    = implode(",",$cc_email);
		$bcc		 = 'marlope@pricon.ph,ronfern@pricon.ph';
		$from		 = 'issinforservice@pricon.ph';
		$from_name	 = 'TQTS Mailer';
		$subject	 = "Inspection Trouble Notice - ".$row_data['control_no'];
		$message 	 = 'Good Day! <br><br>';
		$message 	.= 'ITN Details: - PENDING - (Result of Confirmation)<br>';
		$message 	.= 'Project: '.$row_data['project'].'<br>';
		$message 	.= 'Model: '.$row_data['model'].'<br>';
		$message 	.= 'Issuance Date: '.$row_data['issuance_date'].'<br>';
		$message 	.= 'Standard Specifications: '.$row_data['standard_specification'].'<br>';
		$message 	.= 'Findings Problem: '.$row_data['findings_problem'].'<br>';
		$message 	.= '<br>Please login to Rapid with this link http://rapid <br><br>';
		$message 	.= 'This is a system message generated by the system, Please do not reply!';
		$send_date_time = date('Y-m-d H:i:s');
		require_once('../class/send_email.php');
		$email = new email;
		$mailer_result = $email->send_email_detailed($to_email, $from, $from_name, $cc_email, $bcc, $subject, $message, $send_date_time, $_POST['username']);
		$return['mail_data'] 		= $mailer_result;
		/* Send mail to mailer - end */		
		echo json_encode($return);
	 }
	 
	 function lqc_result_of_confirmation_update_status(){
		require_once('../class/oop_tqts.php');
		$error							= array();
		$return							= $_POST;
		$pkid 							= $_POST['pkid'];
		if($_POST['result_confirmation'] == ""){
			$error[] = "Result of confirmation could not be blank!";
		}
		if( ($_POST['result_confirmation'] != "") && (str_replace(" ", "", $_POST['result_confirmation']) == "") ){
			$error[] = "Result of confirmation could not be blank!";
		}
		if( count($error) != 0 ){
			$return['error'] = $error;
			echo json_encode($return);
			exit;
		}
		$_POST['status']				= '3';
		$_POST['rc_date']				= date('Y-m-d H:i:s');
		$_POST['lastupdate']			= date('Y-m-d H:i:s');
		$table							= 'tbl_qfr_itn';
		$array_field_values 			= get_fields_values($_POST,array('action','pkid'));
		$array_fields 					= $array_field_values['array_fields'];
		$array_values 					= $array_field_values['array_values'];
		$result = TQTS::getInstance()->update_query($table,$array_fields,$array_values,$pkid);
		$script = TQTS::getInstance()->update_query_script($table,$array_fields,$array_values,$pkid);
		$return['script'] = $script;
		$return['array_field_values'] 	= $array_field_values;
		$return['error'] 				= $error;
		/* Send mail to mailer */
		$row_data 	= get_itn_row_data($pkid);
		$mail_data  = array();
		$to_email 	= array();
		$attention  = explode('|',$row_data['attention']);
		foreach($attention as $key => $username){
			$to_email[] = return_user_email_add($username);
		}	
		$cc_email 	 = array();
		$to_email    = implode(",",$to_email);
		$cc_email    = implode(",",$cc_email);
		$bcc		 = 'marlope@pricon.ph,ronfern@pricon.ph';
		$from		 = 'issinforservice@pricon.ph';
		$from_name	 = 'TQTS Mailer';
		$subject	 = "(CLOSED) Inspection Trouble Notice - ".$row_data['control_no'];
		$message 	 = 'Good Day! <br><br>';
		$message 	.= 'ITN Details: - CLOSED<br>';
		$message 	.= 'Project: '.$row_data['project'].'<br>';
		$message 	.= 'Model: '.$row_data['model'].'<br>';
		$message 	.= 'Issuance Date: '.$row_data['issuance_date'].'<br>';
		$message 	.= 'Standard Specifications: '.$row_data['standard_specification'].'<br>';
		$message 	.= 'Findings Problem: '.$row_data['findings_problem'].'<br>';
		$message 	.= '<br>Please login to Rapid with this link http://rapid <br><br>';
		$message 	.= 'This is a system message generated by the system, Please do not reply!';
		$send_date_time = date('Y-m-d H:i:s');
		require_once('../class/send_email.php');
		$email = new email;
		$mailer_result = $email->send_email_detailed($to_email, $from, $from_name, $cc_email, $bcc, $subject, $message, $send_date_time, $_POST['username']);
		$return['mail_data'] 		= $mailer_result;
		/* Send mail to mailer - end */		
		echo json_encode($return);
	 }
	/* ITN - End */
	?>