<?php

class email {
	function send_email($to, $from, $cc, $subject, $body,$attachment,$attachment_name) {
		$body = str_replace("\n","<br>",$body);
		// require_once("../../includes/PHPMailer/class.phpmailer.php");
		require_once("../../media/PHPMailer_SMTP/PHPMailerAutoload.php");
		$mail = new PHPMailer();
		$mail->IsSMTP();
		$mail->SMTPDebug = 1;
		/* old email
		$mail->Host 		= '192.168.3.254';
		$mail->SMTPAuth 	= true;
		$mail->SMTPSecure 	= 'none';
		$mail->Username 	= 'issinfoservice';
		$mail->Password 	= 'pmi1234';
		$mail->Port 		= '25';
		*/
		$mail->Host 		= 'mail3.pricon.ph';
		$mail->SMTPAuth 	= true;
		$mail->SMTPSecure 	= 'ssl';
		$mail->Username 	= 'issinfoservice@pricon.ph';
		$mail->Password 	= 'EYGEKFwlzuDfNufG2DGk';
		$mail->Port 		= '465';
		
		$mail->IsHTML(true);
		if($to != '') {
			$to = explode(",",$to);
			for($i=0; $i<sizeof($to);$i++) {
				$mail->AddAddress($to[$i]);	
			}
		}
		if($cc != '') {
			$cc = explode(",",$cc);
			for($i=0; $i<sizeof($cc);$i++) {
				$mail->AddCC($cc[$i]);	
			}
		}
        
		// $body .= "This E-mail is automatically generated by Total Quality Tracking System. <br>";
		// $body .= "Don't reply to this e-mail, this is only a notification created by the system, Thank you!</i>";
        $body .= "<br><br>Notice of Disclaimer:<br>
                    This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message. Any disclosure,copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.
";
		// $body .= "TO: ".$to."<br>";
		// $body .= "FROM: ".$from."<br>";
		// $body .= "CC: ".$cc."<br>";
		// $mail->AddAddress('rdfernandez@pricon.ph');	//change novs 2019-07-27
		// $mail->AddCC('rdfernandez@pricon.ph');		//change novs 2019-07-27
		$mail->AddAddress('dbretusto@pricon.ph');	//change novs 2019-07-27
		$mail->AddCC('dbretusto@pricon.ph');		//change novs 2019-07-27
		
		$mail->From = $from;
		$mail->FromName = $from;
		// $mail->FromName = "Total Quality Tracking System";
		$mail->AddBCC("dbretusto@pricon.ph");
		$mail->AddBCC("dbretusto@pricon.ph");
		$mail->Subject = $subject;
		$mail->Body= $body;
		
        if($attachment != '') {
            $mail->AddAttachment($attachment, $attachment_name);
        }
        
		if(!$mail->Send())
		{
		   $msg = "Message could not be sent.";
		   $msg .= "Mailer Error: " . $mail->ErrorInfo ."\n";
		   exit;
		} else {
			$msg = "Message has been sent!";
		}
		return $msg; 
	}
}
?>